#!/bin/sh

USERNAME=${USERNAME:-'mysql'}
PASSWORD=${PASSWORD:-'mysql'}
DATABASE=${DATABASE:-'*'}
REMOTE=${REMOTE:-'%'}

service mysqld start

sleep 2

mysql -e "GRANT ALL PRIVILEGES ON $DATABASE.* TO '$USERNAME'@'$REMOTE' IDENTIFIED BY '$PASSWORD'"

service mysqld stop

mysqld_safe
