#!/bin/sh

USERNAME=${USERNAME:-mysql}
PASSWORD=${PASSWORD:-mysql}
DATABASE=${DATABASE:-'*'}
REMOTE=${REMOTE:-'*'}

service mysqld start

sleep 2

mysql -e "GRANT ALL PRIVILEGES ON $DATABASE.* TO $USERNAME@$REMOTE IDENTIFIED BY '$PASSWORD'"

sleep 2

tail /var/log/mysqld.log
